Repository urdego/Urdego_User_Service, pull requests merged in 2025-01, with the labels that each got.

#6 Feature/#3: 애플 소셜 로그인 구현
  build.gradle
  labels.json
  src/main/java/io/urdego/urdego_user_service/api/apple/AppleController.java
  src/main/java/io/urdego/urdego_user_service/api/apple/dto/AppleAuthResponse.java
  src/main/java/io/urdego/urdego_user_service/api/kakao/KakaoController.java
  src/main/java/io/urdego/urdego_user_service/auth/UserPrincipal.java
  src/main/java/io/urdego/urdego_user_service/auth/service/OAuthService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/OAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/auth/service/apple/AppleAuthService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/apple/AppleAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/auth/service/kakao/KakaoAuthService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/kakao/KakaoAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/common/config/FeignConfig.java
  src/main/java/io/urdego/urdego_user_service/common/config/RedisConfig.java
  src/main/java/io/urdego/urdego_user_service/common/enums/PlatformType.java
  src/main/java/io/urdego/urdego_user_service/common/enums/Role.java
  src/main/java/io/urdego/urdego_user_service/domain/entity/User.java
  src/main/java/io/urdego/urdego_user_service/domain/entity/constant/PlatfromType.java
  src/main/java/io/urdego/urdego_user_service/domain/entity/dto/AppleUserInfoDto.java
  src/main/java/io/urdego/urdego_user_service/domain/entity/dto/KakaoUserInfoDto.java
  src/main/java/io/urdego/urdego_user_service/domain/entity/dto/UserResponse.java
  src/main/java/io/urdego/urdego_user_service/domain/entity/dto/UserSignUpRequest.java
  src/main/java/io/urdego/urdego_user_service/domain/repository/UserRepository.java
  src/main/java/io/urdego/urdego_user_service/domain/service/UserService.java
  src/main/java/io/urdego/urdego_user_service/domain/service/UserServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/AppleAuthFeignClient.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/AppleClientSecretGenerator.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/AppleTokenService.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/AppleTokenVerifier.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/dto/AppleTokenReponse.java
  src/main/java/io/urdego/urdego_user_service/infra/kakao/KakaoProfileFeignClient.java
  src/main/java/io/urdego/urdego_user_service/infra/kakao/dto/KakaoUserInfoDto.java
Labels: ✨ Feature

#7 Refactor/#3: application 실행 관련 문제 수정
  build.gradle
  src/main/java/io/urdego/urdego_user_service/UrdegoUserServiceApplication.java
  src/main/java/io/urdego/urdego_user_service/auth/service/OAuthService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/OAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/auth/service/kakao/KakaoAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/common/config/FeignConfig.java
  src/main/java/io/urdego/urdego_user_service/common/config/RedisConfig.java
  src/main/java/io/urdego/urdego_user_service/common/properties/AppleOAuthProperty.java
  src/main/java/io/urdego/urdego_user_service/common/properties/KakaoOAuthProperty.java
  src/main/java/io/urdego/urdego_user_service/common/properties/OAuthProperty.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/AppleAuthFeignClient.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/AppleClientSecretGenerator.java
  src/main/java/io/urdego/urdego_user_service/infra/apple/AppleTokenVerifier.java
Labels: 🐞 BugFix, 🔨 Refactor

#13 Feature(#12): CI 구축
  .github/ISSUE_TEMPLATE/workflows/CI_dev_be_pull_request.yml
Labels: ✨ Feature

#14 Feature(#12): CI test
  src/main/java/io/urdego/urdego_user_service/UrdegoUserServiceApplication.java
Labels: ✨ Feature

#10 Feature/#9: Spring Security + jwt 추가
  src/main/java/io/urdego/urdego_user_service/api/UserController.java
  src/main/java/io/urdego/urdego_user_service/api/apple/AppleController.java
  src/main/java/io/urdego/urdego_user_service/api/apple/dto/AppleLoginRes.java
  src/main/java/io/urdego/urdego_user_service/api/apple/dto/AppleUserInfoDto.java
  src/main/java/io/urdego/urdego_user_service/api/kakao/KakaoController.java
  src/main/java/io/urdego/urdego_user_service/api/kakao/dto/KakaoUserInfoDto.java
  src/main/java/io/urdego/urdego_user_service/api/user/UserController.java
  src/main/java/io/urdego/urdego_user_service/api/user/dto/request/DrawalRequest.java
  src/main/java/io/urdego/urdego_user_service/api/user/dto/request/TokenRefreshRequest.java
  src/main/java/io/urdego/urdego_user_service/api/user/dto/request/UserSignUpRequest.java
  src/main/java/io/urdego/urdego_user_service/api/user/dto/response/UserResponse.java
  src/main/java/io/urdego/urdego_user_service/auth/config/CorsConfig.java
  src/main/java/io/urdego/urdego_user_service/auth/config/SecurityConfig.java
  src/main/java/io/urdego/urdego_user_service/auth/jwt/AuthConstants.java
  src/main/java/io/urdego/urdego_user_service/auth/jwt/JwtFilter.java
  src/main/java/io/urdego/urdego_user_service/auth/jwt/JwtService.java
  src/main/java/io/urdego/urdego_user_service/auth/jwt/JwtUtil.java
  src/main/java/io/urdego/urdego_user_service/auth/redis/RedisConfig.java
  src/main/java/io/urdego/urdego_user_service/auth/redis/RedisService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/CustomUserDetails.java
  src/main/java/io/urdego/urdego_user_service/auth/service/CustomUserDetailsService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/OAuthService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/OAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/auth/service/apple/AppleAuthService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/apple/AppleAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/auth/service/kakao/KakaoAuthService.java
  src/main/java/io/urdego/urdego_user_service/auth/service/kakao/KakaoAuthServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/common/TokenUtils.java
  src/main/java/io/urdego/urdego_user_service/common/exception/BaseException.java
  src/main/java/io/urdego/urdego_user_service/common/exception/ErrorResponse.java
  src/main/java/io/urdego/urdego_user_service/common/exception/ExceptionMessage.java
  src/main/java/io/urdego/urdego_user_service/common/exception/jwt/TokenException.java
  src/main/java/io/urdego/urdego_user_service/common/exception/jwt/TokenRefreshException.java
  src/main/java/io/urdego/urdego_user_service/common/properties/AppleOAuthProperty.java
  src/main/java/io/urdego/urdego_user_service/domain/entity/User.java
  src/main/java/io/urdego/urdego_user_service/domain/service/UserService.java
  src/main/java/io/urdego/urdego_user_service/domain/service/UserServiceImpl.java
  src/main/java/io/urdego/urdego_user_service/infra/kakao/KakaoProfileFeignClient.java
Labels: ✨ Feature, 🔨 Refactor

#17 Test(#16): CI/CD 테스트
  src/main/java/io/urdego/urdego_user_service/UrdegoUserServiceApplication.java
Labels: ✅ Test
